server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisx?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password:

mybatis:
  mapper-locations: classpath:com/lc/mybatisx/test/dao/mapper/*Mapper.xml
  type-aliases-package: com.lc.mybatisx.test.model.entity